version: '3.9'
name: databases
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'MySQL'
      MYSQL_USER: 'app.user'
      MYSQL_PASSWORD: 'app.passwd.'
      MYSQL_ROOT_PASSWORD: '6251'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - H:\docker-data\mysql\data:/var/lib/mysql/