version: '3.9'
name: databases
networks:
  app-network-public:
    driver: bridge

volumes:
  sqldata:
  sqllog:
  sqlbackup:
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    networks:
      - app-network-public
    restart: always
    env_file:
      - conf\sqlserver\sqlserver.env
      - conf\sqlserver\sapassword.env
    ports:
      - '1433:1433'
    volumes:
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - H:\docker-data\sqlserver\shared:/usr/shared
      