version: '3.7'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE=master
            - MONGO_INITDB_ROOT_USERNAME=reivaj2dev
            - MONGO_INITDB_ROOT_PASSWORD=****
        volumes:
            - mongo-data:/data/db
        ports: 
            - 27017:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=reivaj2dev
            - ME_CONFIG_MONGODB_ADMINPASSWORD=****
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_BASICAUTH_USERNAME=reivaj2dev
            - ME_CONFIG_BASICAUTH_PASSWORD=****              
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true         
            - ME_CONFIG_MONGODB_PORT=27017           
            - ME_CONFIG_OPTIONS_EDITORTHEME=default
            - ME_CONFIG_REQUEST_SIZE='100kb        
            - ME_CONFIG_SITE_BASEURL=/             
            - ME_CONFIG_SITE_COOKIESECRET=cookiesecret
            - ME_CONFIG_SITE_SESSIONSECRET=sessionsecret
            #ME_CONFIG_SITE_SSL_ENABLED  ='false'         
            #ME_CONFIG_SITE_SSL_CRT_PATH =''              
            #ME_CONFIG_SITE_SSL_KEY_PATH =''              
volumes:
    conf:
    mongo-data:


        
