version: '3.7'
services:
    sqlserver1:
        restart: always
        build: 
          context: .
          dockerfile: dockerfile
        ports:  
          - "1433:1433"
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
          - C:\Apps\sqlserver\tmp:/tmp #Sustituir por directorio en ordenador local
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: